### ISSUE TITLE
Feedback from projects site

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/window-on-the-weather#5]
URL: /en/projects/window-on-the-weather/5

This is an outdated article and doesn't work with current version of scratch. Please, could it be updated or otherwise deleted?

**Comment by MarcScott** [comment]
This project needs a redirect and then archiving, as it no longer works due to changes in Scratch

**Comment by martinohanlon** [comment]
Archived.

Note on readme, step 1 of the project and unlisted.
